name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install all the dependencies
      run:
        python3 -m pip install --upgrade
        pip install -r requirements.txt
    - name: Lint with flake8
      run:
        flake8
    - name: Django testing
      run:
        python3 manage.py test
    - name: Reloading Server
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'pythonanywhere.com'
        username: 'hnryjsph9'
        api-token: '66ae059404887ef91d6cc7fc13f958ed31e43e32'
        domain-name: 'https://hnryjsph9.pythonanywhere.com'
